/**
 * Homepage marketing copy — edit here to iterate without touching layout.
 * Editorial tone; human review as strongest practical layer, not infallible.
 * Prefer brevity: full narrative lives on /about.
 */

export const homepageCopy = {
  hero: {
    eyebrow: "Human judgment is the final safeguard.",
    title: "Independent citation verification for the bar and the bench",
    body: "AI can draft a convincing citation in seconds—even when the case does not exist or the quotation is wrong. 2dcite adds a qualified human reviewer before an error becomes a filing, a sanction, or a reputational crisis.",
    support:
      "Approved 2L and 3L law students check citations against the underlying authorities and document the work in a Certificate of Citation Review.",
    primaryCta: { label: "Verify my citations", href: "/signup" },
    secondaryCta: { label: "See how it works", href: "/#how-it-works" },
    disclaimer:
      "Independent verification only—not legal advice. Ultimate responsibility remains with the licensed attorney or judge.",
  },

  trustBar: [
    "Human-reviewed",
    "Source-checked",
    "Confidential",
    "Fixed-fee",
    "Documented",
  ],

  humanLoop: {
    id: "why-human",
    eyebrow: "Why human-in-the-loop",
    title: "Automation accelerates the work. Humans verify the truth.",
    lead: "Generative tools produce language that is fast and persuasive—not authoritative. A fabricated case can look real. An altered quotation can sound exact.",
    body: "2dcite inserts an independent reviewer between the draft and professional reliance. The reviewer does not ask another AI whether a cite is correct; they check the underlying authority.",
    checksIntro: "A reviewer evaluates whether:",
    checks: [
      "The cited authority exists and is correctly identified",
      "Quoted language appears in the source",
      "The cited proposition is actually supported",
      "Court, date, and other identifiers are accurate",
      "Material discrepancies should be flagged to the submitter",
    ],
    resultTitle: "Technology-speed work with human accountability",
    resultBody:
      "No process guarantees a flawless filing. Human review adds judgment, skepticism, and source-level inspection—safeguards automated output cannot provide on its own.",
  },

  /** Merged: risk + duty + independence — one scannable narrative */
  whyItMatters: {
    id: "why-it-matters",
    eyebrow: "Why verification matters",
    title: "Fake citations create real consequences.",
    lead: "Courts have sanctioned attorneys for nonexistent cases, fabricated quotations, and inaccurate authorities—including AI-generated material filed without adequate verification. Attorneys face sanctions, fee awards, disciplinary referrals, practice restrictions, and potentially career-altering consequences when citations go unchecked.",
    caseNote:
      "In Mata v. Avianca, counsel were sanctioned after submitting nonexistent decisions and fabricated quotations generated by ChatGPT, then defending those cites after the court questioned them.",
    lesson:
      "Using AI may save time. Failing to verify its work can put a career, a client, and a case at risk.",
    dutyTitle: "The duty does not change because the tool changed",
    dutyBody:
      "ABA Formal Opinion 512 makes clear that lawyers using generative AI remain responsible for competence, supervision, candor, and the accuracy of work submitted in a client’s name. AI does not sign the filing, answer the court, or bear professional responsibility—the attorney does.",
    independentTitle: "You should not have to grade your own work",
    independentBody:
      "The drafter knows what a sentence was meant to say and may read that meaning into the cited authority. An independent reviewer checks the source without that assumption. Independent review is not a substitute for attorney judgment—it is a safeguard for it.",
    findsIntro: "A second set of eyes can uncover:",
    finds: [
      "Hallucinated cases and misquoted opinions",
      "Wrong authorities or unsupported propositions",
      "Incorrect courts, dates, or reporter information",
      "Errors carried forward from templates or prior filings",
    ],
  },

  howItWorks: {
    id: "how-it-works",
    title: "How 2dcite works",
    intro:
      "Four steps from upload to certificate. Liability remains with you; the student provides independent verification only.",
    steps: [
      {
        step: 1,
        title: "Upload your document",
        body: "Submit a brief, proposed order, or table of authorities—before or after filing.",
      },
      {
        step: 2,
        title: "Receive an independent review",
        body: "An approved 2L or 3L, bound by confidentiality, checks citations against the underlying sources.",
      },
      {
        step: 3,
        title: "Review the findings",
        body: "You alone decide any correction, errata, withdrawal, or other action under applicable rules.",
        emphasize: true,
      },
      {
        step: 4,
        title: "Document the process",
        body: "A Certificate of Citation Review evidences that independent verification was completed.",
      },
    ],
    cta: { label: "Start a citation review", href: "/signup" },
  },

  certificate: {
    id: "certificate",
    title: "Verification should leave a record.",
    lead: "A verbal assurance that someone “looked it over” is hard to document. The Certificate of Citation Review records that an independent citation review was performed—and may be retained for internal risk management or used as otherwise permitted.",
    pointsIntro: "It demonstrates process, not perfection:",
    points: [
      "An independent review was requested and completed",
      "Citation verification was a distinct workflow step",
      "The submitter took an affirmative risk-mitigation measure",
    ],
    disclaimer:
      "The certificate is not a warranty of accuracy, completeness, or outcome and does not transfer the licensed professional’s responsibility.",
  },

  closing: {
    id: "get-started",
    title: "Before you rely on a citation, verify it.",
    body: "One false authority can undermine an otherwise sound argument and create consequences far beyond the page it appears on. Add an independent human verification layer to your filing workflow.",
    primaryCta: { label: "Verify my citations", href: "/signup" },
    secondaryCta: { label: "View pricing", href: "/#pricing" },
    note: "Standard, rush, or membership ($99/mo with 1 included review + 10% off extras).",
    tagline: "AI can generate the citation. Only verification earns your confidence.",
    campaign: "Don’t trust the formatting. Verify the authority.",
  },

  resources: {
    id: "resources",
    title: "Selected authorities",
    intro: "Public materials on generative AI and citation integrity.",
    links: [
      {
        label: "ABA Formal Opinion 512",
        description: "Generative AI tools and lawyer ethics duties",
        href: "https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/ethics-opinions/aba-formal-opinion-512.pdf",
      },
      {
        label: "Mata v. Avianca (S.D.N.Y.)",
        description:
          "Sanctions for nonexistent opinions with fabricated quotations and citations",
        href: "https://law.justia.com/cases/federal/district-courts/new-york/nysdce/1%3A2022cv01461/575368/54/",
      },
    ],
  },

  studentPath: {
    title: "Law students",
    body: "2L/3L applicants with a .edu email may apply after meeting eligibility requirements and admin review.",
    cta: { label: "Apply as a student", href: "/signup?role=student" },
  },
} as const;
